### ISSUE TITLE
Rich presence doesnt work.

### ISSUE THREAD

**Issue by ZapadniLes** [xHyroM/zed-discord-presence#1]
Idk if I am just stupid but it's just not working. I did exactly as instructed in the readme. I cloned the repository and try to install it with zed: install dev extension. I have Rust installed and I also have enabled displaying detected activity on Discord. 
I have Manjaro (linux) and Vencord but i dont think it is why it's not working.

**Comment by xHyroM** [comment]
> Idk if I am just stupid but it's just not working. I did exactly as instructed in the readme. I cloned the repository and try to install it with zed: install dev extension. I have Rust installed and I also have enabled displaying detected activity on Discord. I have Manjaro (linux) and Vencord but i dont think it is why it's not working.

First, check, if the extension is listed in the extension tab. If not, install the dev extension again and send me logs from `zed: open log`. If it's there, restart Zed and send logs also from `debug: open language servers logs`.

**Comment by ZapadniLes** [comment]
Oh, that won't be necessary, thanks. I've fixed it. I found in the log that the error was that the system couldn't find the rustup because it was missing in the PATH. Thanks for your help and your time.

**Comment by xHyroM** [comment]
Nice! If you experience something, just contact me again 😄😅. Yeah, zed requires rustup for building dev extensions, don't know why 🤷. Also thanks for star ⭐.
