### ISSUE TITLE
failed to download file

### ISSUE THREAD

**Issue by tarosbubbletea** [xhyrom/zed-discord-presence#18]
![image](https://github.com/user-attachments/assets/91dbeaf2-280b-46c3-a56f-2b2603cb0e88)
```
2024-10-27T13:23:10.790551-03:00 [INFO] starting language server process. binary path: "C:\\Users\\taro\\AppData\\Local\\Zed\\extensions\\work\\discord-presence\\discord-presence-lsp-v0.5.1\\discord-presence-lsp-x86_64-pc-windows-msvc\\discord-presence-lsp", working directory: "C:\\laragon\\www\\api", args: []
2024-10-27T13:23:11.4626797-03:00 [ERROR] Failed to start language server "discord_presence": failed to download file: failed to unzip discord-presence-lsp-v0.5.1 archive
2024-10-27T13:23:11.4627513-03:00 [ERROR] server stderr: ""
```

**Comment by xhyrom** [comment]
Looks like the file got corrupted because it cannot be unzipped. Try to remove everything in `C:\\Users\\taro\\AppData\\Local\\Zed\\extensions\\work\\discord-presence` or download the zip yourself from https://github.com/xhyrom/zed-discord-presence/releases/tag/v0.5.1 and unzip it in the folder.

**Comment by tarosbubbletea** [comment]
loads fine now, but (not sure if it's intended behavior) the status doesn't update when I switch files or close tabs, and it picks up the 2nd tab from the left as the currently open file by default. I'll close the issue because the main problem at hand is solved, thanks

**Comment by xhyrom** [comment]
> loads fine now, but (not sure if it's intended behavior) the status doesn't update when I switch files or close tabs, and it picks up the 2nd tab from the left as the currently open file by default. I'll close the issue because the main problem at hand is solved, thanks

Due to LSP limitations the status updates only when you write something to the file

**Comment by CantCode023** [comment]
im on windows build and for me this extension never seem to does work, i always get this the same error as the picture from OP, even  though the file has actually been successfully extracted, sometimes the extension works but it only shows "Idling", when I try to change the config it'll refresh the extension and says "Editing settings.json" which is good but when I switch to another file and editing the file, it doesn't change and after some time it goes back to "Idling".
