### ISSUE TITLE
not working in macOS

### ISSUE THREAD

**Issue by popoyPOY** [xhyrom/zed-discord-presence#19]
It shows this error:

![image](https://github.com/user-attachments/assets/1b524607-d46f-4054-801a-ec24777eec62)

Please help, thank you

**Comment by xhyrom** [comment]
Does rich presence works from different applications? Also how did you install the discord app?

**Comment by popoyPOY** [comment]
I'm barely new to Zed. I install discord app using its discord.com website
![image](https://github.com/user-attachments/assets/2b9433ca-e03e-441e-8d9c-440a93e8060d)
![image](https://github.com/user-attachments/assets/03225e07-bd09-4766-a37e-e3547bd3e2fc)

**Comment by xhyrom** [comment]
Then it should work :thinking: Can you try different application with rich presence support to see if it works?

**Comment by popoyPOY** [comment]
Hi @xhyrom,

Thank you, its my fault I disabled the rich presence on discord.

![Uploading image.png…]()

**Comment by ItzSwirlz** [comment]
I have it enabled and I'm getting inconsistency issues here too.
