### ISSUE TITLE
not working in discord ptb

### ISSUE THREAD

**Issue by srv03rtm** [xhyrom/zed-discord-presence#2]
hey, the extention doesnt work on discord ptb for some reason, not sure why

**Comment by xHyroM** [comment]
Hello, first, check, if the extension is listed in the extension tab. If not, install the dev extension again and send me logs from `zed: open log` (you can get them from `~/.local/share/zed/logs/Zed.log`. If it's there, restart Zed and send logs also from `debug: open language servers logs`.

**Comment by xhyrom** [comment]
Marked as stale, reopen if it still doesn't work.

**Comment by xhyrom** [comment]
> hey, i cross checked everything, no errors

Can you send me the log please? Can you try installing the dev extension again and check if it's in the extensions list? Also what's your operating system and does discord rp works from other programs (how did you install discord)?

**Comment by Alleexxi** [comment]
I got the same problem (I am on WIndows). 
When you are on WIndows Zed needs admin privileges to install a dev extension. I did that and it works now

**Comment by xhyrom** [comment]
> I got the same problem (I am on WIndows). When you are on WIndows Zed needs admin privileges to install a dev extension. I did that and it works now

That's related to https://github.com/xhyrom/zed-discord-presence/issues/3
