### ISSUE TITLE
Laravel and PHP are not displaying correctly

### ISSUE THREAD

**Issue by ralphsun73221** [xhyrom/zed-discord-presence#21]
This is my environment information:
![20241119-sunzhengjie@RALPH-M2-Max~DeveloperPHPLaravel@2x](https://github.com/user-attachments/assets/6b9876d1-6817-4abc-a9b4-cea3799b0fc9)

Discord Presence Version: 0.2.1

Normally it should display successfully:
![image](https://github.com/user-attachments/assets/fb3a6a43-3314-41a3-bd9f-d58a3cad964e)

However, when I use PHP, it becomes like this:
![image](https://github.com/user-attachments/assets/480b88ab-9d9f-49e0-91e2-3eef2be1c00c)

I initially thought it was because there was no PHP icon provided in https://raw.githubusercontent.com/xhyrom/zed-discord-presence/main/assets/icons/, but after checking, I found that there is one.

And if my Workspace is Laravel, it doesn't display at all:
![image](https://github.com/user-attachments/assets/a0e94d25-1082-4af6-ba9c-151b120561ad)

The first one can display normally because my workspace name is not Laravel.

If you need any further information, please let me know. Thank you.

**Comment by xhyrom** [comment]
There's probably issue with regex in https://github.com/xhyrom/zed-discord-presence/blob/79b39ca2cadd393ffa5915055d44688dcdb5ecbb/assets/languages.json#L287

--

I think laravel should work as expected, isn't it just a bunch of php files?
