### ISSUE TITLE
Ability to change the App ID

### ISSUE THREAD

**Issue by kyuiki** [xhyrom/zed-discord-presence#22]
Is it possible to change the App ID so that I can use my own Discord App ID? Just like in Visual Code Studio Discord Rich Presence. 
(Highlighted Yellow)
![image](https://github.com/user-attachments/assets/f86eba3e-2c3e-4bd1-99f2-b16854456534)

It would be awesome so I can use it on my own for fully customizable rich presence

**Comment by xhyrom** [comment]
Thanks for your feature request! I'll add it ;)
