### ISSUE TITLE
Extension not working using Windows build

### ISSUE THREAD

**Issue by nitayStain** [xhyrom/zed-discord-presence#3]
![image](https://github.com/user-attachments/assets/a66c0376-2851-4555-944a-6375177fb8c8)
Hey! The log file shows this. This is certainly an OS error due to the log type.

**Comment by xHyroM** [comment]
> Hi, does the presence works from other clients? I don't have windows so i didn't try the extension on it, but this is probably something from [discord_rich_presence](https://docs.rs/discord-rich-presence/latest/discord_rich_presence/) when it tries to create socket.

After trying this with empty extension that doesn't download lsp this happens too. Seems related to something different, I've never met this.

**Comment by JunkuiZhang** [comment]
When developing an extension, Zed performs some symbolic link operations. For certain reasons, creating symbolic links on Windows requires administrator privileges. Therefore, you need to run Zed as an administrator. See:

https://github.com/zed-industries/zed/pull/9365
