### ISSUE TITLE
show language icons in large image

### ISSUE THREAD

**Issue by darkyeg** [xhyrom/zed-discord-presence#5]
Hello, I would like to support the large image feature. You can use the images from [this repository](https://github.com/leonardssh/vscord) to implement this feature if possible.

**Comment by xhyrom** [comment]
Sure, I can add support for that. 😄

**Comment by darkyeg** [comment]
> Sure, I'll add support for that. 😄

I can work on it if you haven't started yet. 😊

**Comment by xhyrom** [comment]
> > Sure, I'll add support for that. 😄
> 
> I can work on it if you haven't started yet. 😊

I'll start today but I'm currently in a car 😄. Going home from vacation.

**Comment by xhyrom** [comment]
Landed in 0.4.0 https://github.com/xhyrom/zed-discord-presence/releases/tag/v0.4.0
