### ISSUE TITLE
Ability to enable/disable rich presence in specific workspaces

### ISSUE THREAD

**Issue by nekotori55** [xhyrom/zed-discord-presence#9]
Is there a way to temporarily disable rich presence?

I think this is a useful feature. Currently I'm just uninstalling/installing the extension, but it's not particularly convenient

**Comment by nekotori55** [comment]
In fact, this should be a zed feature, and there is even an issue for it. I'll change the question to disabling presence in specific workspaces then.

**Comment by xhyrom** [comment]
Sure, i'll implement this. Thanks for a such great idea!

**Comment by xhyrom** [comment]
https://github.com/xhyrom/zed-discord-presence?tab=readme-ov-file#how-to-configure "rules" part
